spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/mysql
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl:
        auto: none
    show-sql: true
